### DISCUSSION TITLE
Setting temp on auto-mode

### DISCUSSION THREAD

**Discussion by patrickcollins12** [revk/xESP32-Faikout#623] [General]
I've been looking at the [Advanced](https://github.com/revk/ESP32-Faikin/blob/main/Manuals/Advanced.md) documentation.

I have a BME280 temperature sensor in my room which seems a lot more accurate than the temperature sensor built into my daikin.

I'd like to publish the "current temperature" from this external device. Via home assistant I could set this up I guess.

I have 2 questions:
Using MQTT where do I publish the current temperature?  I did publish to here `command/faikinstudy/env` but it gets overwritten by the air conditioner.

Should I add the BME280 temperature sensor directly to the Faikin unit for more accurate temperature readings and is there documentation on how to do that? I can solder if needed.

<img width="863" alt="image" src="https://github.com/user-attachments/assets/74621901-7165-498c-927a-3b3ec94d0290" />

![image](https://github.com/user-attachments/assets/af5ec423-dda3-4da6-af5a-add76532ae6a)

**Comment by revk** [comment]
You want `command/faikinstudy/control` with `{"env":26.1}` for example.

Or you could have the Faikin track the sensor directly if it can see it.

**Comment by patrickcollins12** [comment]
Boom. That worked out of the box thanks.

So I'd just solder the bme280 onto a spare gpio?


```
alias: Publish BME280 to Faikinstudy
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.bme280_temperature
conditions: []
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: command/faikinstudy/control
      payload: "{\"env\": {{ states('sensor.bme280_temperature') }} }"
```
