### DISCUSSION TITLE
S21 does not seem to expose powerful setting (CTXS07LVJU)

### DISCUSSION THREAD

**Discussion by pfak** [revk/xESP32-Faikout#86] [Q&A]
Powerful set via remote on CTXS07LVJU:

```
{"G1":"13NA","G2":"=;\u0000�","G3":"0��\u0000","G4":"05�\u0000","G5":"000�","G8":"0\u0000\u0000\u0000","SH":"502+","SI":"551+","Sa":"022+","SL":"811","Sd":"710","SN":"060+","SX":"081+","SD":"000"}
```

No powerful:

```
{"G1":"13NA","G2":"=;\u0000�","G3":"0��\u0000","G4":"05�\u0000","G5":"000�","G8":"0\u0000\u0000\u0000","SH":"591+","SI":"551+","Sa":"022+","SL":"580","Sd":"330","SN":"060+","SX":"062+","SD":"000"}
```

Thoughts?

**Comment by pfak** [comment]
Am I reading this right?

```
{
  "G1": "13NA",			// Basic status
  "G2": "=;\u0000�",		// ?? (not defined in https://github.com/revk/ESP32-Faikin/blob/main/ESP32/main/Faikin.c#L320C1-L320C1)
  "G3": "0��\u0000",		// ??
  "G4": "05�\u0000",		// ??
  "G5": "000�",			// Swing status
  "G8": "0\u0000\u0000\u0000",	// ??
  "SH": "002+",			// home temp
  "SI": "541+",			// liquid
  "Sa": "022+",			// outside temp
  "SL": "570",			// ??
  "Sd": "000",			// ??
  "SN": "060+",			// ??
  "SX": "062+",			// ??
  "SD": "000"			// ??
}
```

**Comment by pfak** [comment]
18C, Auto, Cool:

```
{
  "G1": "13@A",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "012+",
  "SI": "561+",
  "Sa": "022+",
  "SL": "480",
  "Sd": "000",
  "SN": "060+",
  "SX": "091+",
  "SD": "000"
}

{
  "G1": "13@A",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "012+",
  "SI": "531+",
  "Sa": "022+",
  "SL": "480",
  "Sd": "320",
  "SN": "060+",
  "SX": "091+",
  "SD": "000"
}
```

19C, Auto, Cool:

```
{
  "G1": "13@A",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "012+",
  "SI": "541+",
  "Sa": "022+",
  "SL": "580",
  "Sd": "000",
  "SN": "060+",
  "SX": "091+",
  "SD": "000"
}
{
  "G1": "13BA",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "012+",
  "SI": "041+",
  "Sa": "022+",
  "SL": "580",
  "Sd": "320",
  "SN": "060+",
  "SX": "002+",
  "SD": "000"
}
```

20C, Auto, Cool:

```
{
  "G1": "13BA",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "012+",
  "SI": "071+",
  "Sa": "022+",
  "SL": "580",
  "Sd": "000",
  "SN": "060+",
  "SX": "002+",
  "SD": "000"
}
{
  "G1": "13DA",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "012+",
  "SI": "041+",
  "Sa": "022+",
  "SL": "670",
  "Sd": "320",
  "SN": "060+",
  "SX": "012+",
  "SD": "000"
}
```

Powerful:

```
{
  "G1": "13DA",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "012+",
  "SI": "041+",
  "Sa": "022+",
  "SL": "701",
  "Sd": "320",
  "SN": "060+",
  "SX": "081+",
  "SD": "000"
}
```

**Comment by pfak** [comment]
`SX` seems to indicate some kind of status w/ regards to cooling.

**Reply by JeanOlivier** [reply]
It looks like the temperature target to me. Considering it's reversed like @revk said below.
Powerful setting it to +18.0 for a few minutes sounds reasonable.

**Comment by pfak** [comment]
Off:

```

{
  "G1": "03DA",
  "G2": "=;\u0000�",
  "G3": "0��\u0000",
  "G4": "05�\u0000",
  "G5": "000�",
  "G8": "0\u0000\u0000\u0000",
  "SH": "002+",
  "SI": "031+",
  "Sa": "532+",
  "SL": "000",
  "Sd": "810",
  "SN": "921+",
  "SX": "012+",
  "SD": "000"
}
```

**Comment by revk** [comment]
Remember the S values are read backwards, eg "012+" is +21.0C, if that helps.

**Comment by JeanOlivier** [comment]
Here are results on my CTXS09HVJU unit:

For the cooling mode, target was set to 21°C

1. Unit Off, last used mode was AC cooling targetting 21°C:
``` yaml
{
 'G1': '03F7',
 'G2': '=;\\u0000\x80',
 'G3': '0000',
 'G4': '0\\u0000\x80\\u0000',
 'G5': '000\x80',
 'G8': '0\\u0000\\u0000\\u0000',
 'SH': '032+',
 'SI': '091+',
 'Sa': '521+',
 'SL': '000',
 'Sd': '000',
 'SN': '090+',
 'SX': '022+',
 'SD': '000'
}
```

2. Unit ON, cooling, powerful OFF
``` yaml
{
 'G1': '13F7',
 'G2': '=;\\u0000\x80',
 'G3': '0000',
 'G4': '0\\u0000\x80\\u0000',
 'G5': '000\x80',
 'G8': '0\\u0000\\u0000\\u0000',
 'SH': '032+',
 'SI': '002+',
 'Sa': '521+',
 'SL': '910',
 'Sd': '000',
 'SN': '710+',
 'SX': '022+',
 'SD': '000'
}
```

3. Unit ON, cooling, powerful ON
``` yaml
{
 'G1': '13F7',
 'G2': '=;\\u0000\x80',
 'G3': '0002',
 'G4': '0\\u0000\x80\\u0000',
 'G5': '000\x80',
 'G8': '0\\u0000\\u0000\\u0000',
 'SH': '032+',
 'SI': '002+',
 'Sa': '521+',
 'SL': '711',
 'Sd': '000',
 'SN': '500+',
 'SX': '081+',
 'SD': '000'
}
```

4. Unit ON, cooling, powerful OFF
``` yaml
{
 'G1': '13F7',
 'G2': '=;\\u0000\x80',
 'G3': '0000',
 'G4': '0\\u0000\x80\\u0000',
 'G5': '000\x80',
 'G8': '0\\u0000\\u0000\\u0000',
 'SH': '032+',
 'SI': '091+',
 'Sa': '521+',
 'SL': '931',
 'Sd': '010',
 'SN': '050+',
 'SX': '022+',
 'SD': '000'
}
```

5. Unit OFF
``` yaml
{
 'G1': '03F7',
 'G2': '=;\\u0000\x80',
 'G3': '0000',
 'G4': '0\\u0000\x80\\u0000',
 'G5': '000\x80',
 'G8': '0\\u0000\\u0000\\u0000',
 'SH': '032+',
 'SI': '002+',
 'Sa': '521+',
 'SL': '760',
 'Sd': '010',
 'SN': '710+',
 'SX': '022+',
 'SD': '000'
}
```

It looks like G3 is '0002' when powerful is active in my case and '0000' otherwise.
It could also be a 20 min timer before it's back to normal, I didn't leave it on long enough to check. 

In powerful mode, SX is '081+', which I presume is the 18°C target. But in non-powerful mode it's '022+' whereas I'd expect '021+'.
Sd (compressor?) also changes with the mode but it's unclear to me what it means. SN is weird as well.

I hope that helps!


PS: MQTT is the weirdest way to talk to devices I ever used.
